server:
  port: 8762
spring:
  cloud:
    config:
      label: master
      uri: http://localhost:8888/
      profile: dev
    bus:
      trace:
        enabled: true
      enabled: true
  application:
    name: eureka-client
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh



